### ISSUE TITLE
Not clear how to add multiple google calendars from the same account

### ISSUE THREAD

**Issue by Nine-H** [elementary/calendar#389] opened 2019-04-09 00:13 UTC
I've successfully added my default calendar from google, but my uni and work schedules aren't synced and adding them manually as calendars named "Uni" and "Work" on my gmail account imports my default calendar.

This is distinct from #81 where google calendars were merged, I think the bug no longer applies to the new app.

**Comment by arkraft** [comment] 2019-04-09 05:46
As a workaround you could try using Gnome Evolution to set up the calendar. Calendar is using EDS as its backend, so every calendar you set up in Evolution will also be visible in Calendar. It supports multiple calendars for the same account. I had problems setting up Google at all and used Evolution to get it working

**Comment by peteruithoven** [comment] 2019-04-09 19:48
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/calendar/issues/16

Quote from #16:
> Just leaving a comment here that I think the plan is to have all online accounts integration for Calendar go through Online Accounts in System Settings. So adding a calendar from an Google account inside of calendar itself will go away. Adding a calendar using Evolution and Google Oauth imports all calendars already, so that's what System Settings needs to do.

**Closed by peteruithoven** 2019-04-09 19:48 UTC
