### ISSUE TITLE
Selecting 'Remove Occurence" from context menu crashes the Calendar

### ISSUE THREAD

**Issue by Andrewsudarikov** [elementary/calendar#491] opened 2020-02-16 17:06 UTC
## Describe the bug
Clicking on the context menu item "Remove occurrence" immediately crashes the program. 

### To Reproduce
1. Create an event. 
2. RIght-click on a new event. 
3. Select "Remove occurence"
4. Voila, the program reliably crashes every time. 

### Expected behavior
An event occurrence for the selected date should be removed. The application must continue running. 

## Platform Information
 - OS: Elementary OS 5
 - OS Version 5.1.2

- [X] I'm using the latest released stable version

**Comment by mcclurgm** [comment] 2020-03-20 18:46
I've been seeing this too. I've found a stack trace for the issue. It's in `EventMenu.vala` line 80. (Following a stack trace from valgrind) It appears that the issue is with setting the exception dates in the call to the Evolution server. Specifically, it's the call to `e_cal_component_set_exdate_list`. 

I'm not sure if this is helpful, but this behavior doesn't appear when adding exceptions in the editor because that uses libical properties, not libecal. Maybe that's helpful to see where this behavior is coming from, I'm not familiar with Evolution.

**Comment by mkykadir** [comment] 2020-04-09 21:07
I think problem relies on line 77 in `EventMenu.vala`, I checked Vala compiler output for `EventMenu.vala` file which is `EventMenu.c` and problem can be seen that `dtstart` is type of `ECalComponentDateTime*` and `e_cal_component_get_dtstart` function receives address of `dtstart`. So it sends address of the pointer which is wrong.

```C	
ECalComponentDateTime* dtstart = NULL;
// ...
ECalComponentDateTime* _tmp1_ = NULL; // this will be dtstart
// ...
#line 68 "/home/mkytr/Projects/calendar/src/Widgets/EventMenu.vala"
g_return_if_fail (self != NULL);
#line 77 "/home/mkytr/Projects/calendar/src/Widgets/EventMenu.vala"
_tmp0_ = self->priv->_comp;
#line 77 "/home/mkytr/Projects/calendar/src/Widgets/EventMenu.vala"
e_cal_component_get_dtstart (_tmp0_, &_tmp1_); // __tmp1__ becomes ECalComponentDateTime**
```
Because of that invalid address is updated so inner library functions gets invalid memory which it cannot access.
 `e_cal_component_get_dtstart` [expects](https://developer.gnome.org/libecal/stable/ECalComponent.html#e-cal-component-get-dtstart) pointer, not the address of the pointer. [Valadoc ](https://valadoc.org/libecalendar-1.2/E.CalComponent.get_dtstart.html) of the libecal-1.2 also states that it expects object itself not the reference of it. This [commit](https://github.com/elementary/calendar/commit/a11723eea73d6d15757a23ce1f71e44dcbf65dc6) makes changes of libecal-1.2 interface and changes local variable types.  I tried to locally revert those changes for `get_dtstart`, but currently I am getting compilation errors.

**Comment by mkykadir** [comment] 2020-04-10 16:25
I've figured out the problem and fixed it but this revealed another problem that lives in deep CalendarModel code I think. Removing an occurance instantiates an `update_event` but this all messes the event. All other occurences are getting removed instead of the selected one. Also anyone noticed that edit panel doesn't enables "Repeat" toggle even repeat is enabled for the event? I am also looking solution for that.

**Comment by mcclurgm** [comment] 2020-04-10 22:37
Great on the fix, looking forward to it! I think I figured out the "repeat" toggle, and I'll be submitting a PR in a few minutes. I'm not sure what you mean about `update_event`, though. If it's related to this issue, could you describe it a little more? Otherwise, that sounds like something that you should open an issue for.

**Comment by mkykadir** [comment] 2020-04-11 07:57
I can send a pull request about this issue to solve the segmentation error problem but this reveals another problem and I think that's more dangerous. Because it can disrupt the events of the user. Opening an issue report about the underlying issue may result in unreproducible issue report since users will get segmentation error way before it. The way recurring events handled in this application seems different that others calendar applications (i.e. GNOME Calendar). This tries to update the main event by adding the selected date as exception date when user tries to remove an occurance of it. But recurrent events have recurrence ids and we can just remove the recurrent event, I think exception dates are not the right way to handle this. So when solution for this issue is applied, wrong behaviour will appear and I think it is more dangerous than this issue. This issue crashes the application but doesn't break down events of the user. I believe that both issues should be resolved in same pull request. But I am open to any recommendations that can solve this situation.

**Closed** 2020-04-30 12:17 UTC
