### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ernmander** [elementary/calendar#239] opened 2018-05-16 10:51 UTC
reminders / notifications don't seem to work with the pre installed calendar.

**Comment by pinkcichlid** [comment] 2018-07-29 03:11
have same issue reminders do nothing

**Comment by laubster** [comment] 2018-11-09 16:33
ditto

**Comment by CodingSpiderFox** [comment] 2019-08-22 09:39
Please describe in detail: what did you expect and what happened instead

I had an issue today: I set an appointment for 9:38 AM with notification 10 minutes in advance. It was already actually 9:37 AM when I was doing this. So I would expect that the notification appears straight away. But instead, at 11:29 AM, I got a notification that said "Test (in 9 minutes)"

**Comment by bbuhler** [comment] 2019-09-19 13:59
For me the notification comes almost 2 hours after the event happend:

![Screenshot from 2019-09-19 15-53-51](https://user-images.githubusercontent.com/2802675/65250678-3a833c80-daf6-11e9-906c-b6b1c1912f70.png)

I assume it is a timezone bug.

**Comment by Juno37** [comment] 2019-11-11 21:43
Reminder does not appear in notification pop up.

Reminder lot listed in missed notifications list.

:-(

Juno 5.0

**Comment by jtrees** [comment] 2020-01-11 10:04
I think this may be related to timezone issues (#92). I just got a notification 1 hour late and have my timezone set to UTC+1. Could this be the case for you too, @bbuhler?

**Comment by camilova** [comment] 2020-05-19 17:04
For me the error is due timezones, because I use GMT-4 and when I set an event at 17:00 h localzone (GMT-4) the alert shows at 13:00 h, als it were UTC. (#92)

**Comment by mcclurgm** [comment] 2020-05-19 21:10
Good points, but I don't think that's everything. I'm working on a time zone fix, and notifications haven't improved for me. They deliver at weird times, and often not at all. So while timezones may fix issues like @jtrees and @camilova are having, there's definitely another issue going on here.

**Comment by fabiozaramella** [comment] 2020-11-14 12:39
Whilst time zones still don't seem to be recognized correctly, notifications are working now after #637 also this is a duplicate of both #474 and #92 so i'm going to close it.

**Closed by fabiozaramella** 2020-11-14 12:39 UTC
Labels: Priority: Medium, Status: Confirmed
