### ISSUE TITLE
"Today" indicator did not update overnight

### ISSUE THREAD

**Issue by panicsteve** [elementary/calendar#480] opened 2019-12-29 16:52 UTC
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
I put my laptop to sleep on the evening of Dec 28, and woke it up on the morning of Dec 29.

Pressing the "Today" button correctly takes me to Dec 29, but the green circle indicating "Today" is still on Dec 28.  (See screenshot)

### To Reproduce
1. Put computer to sleep
2. Wait for date to change
3. Wake computer

### Expected behavior
Green indicator of "Today" should be the same date that the clicking the "Today" button takes you to.

### Screenshots or screen recordings
![Screenshot from 2019-12-29 08 47 50@2x](https://user-images.githubusercontent.com/196190/71559885-409f8800-2a18-11ea-80ac-89772d9718af.png)

### Logs
Can provide logs if necessary. Please let me know where to find them.

## Platform Information
![Screenshot from 2019-12-29 08 51 19@2x](https://user-images.githubusercontent.com/196190/71559927-688eeb80-2a18-11ea-92e0-11a60b29e82f.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context
N/A

**Comment by 4jNsY6fCVqZv** [comment] 2019-12-30 15:39
Can probably be solved in the context of this issue:
https://github.com/elementary/calendar/issues/34
The question for me is: If I leave Calendar app open overnight, then wake up the device from hibernation the following day, should Calendar automatically adjust the current day to the network or device date?

**Comment by mcclurgm** [comment] 2020-03-22 22:55
This is a duplicate of #260. It has more info though, so maybe this one should stay open?

**Comment by 4jNsY6fCVqZv** [comment] 2020-06-12 17:17
@mcclurgm 

> These are two different things, although once the green dot behavior is fixed then maybe we can consider whether to change the gray dot behavior too.

means you could see yourself working on a solution for https://github.com/elementary/calendar/issues/34 as well?

**Comment by 4jNsY6fCVqZv** [comment] 2020-06-12 17:19
@mcclurgm 

> These are two different things, although once the green dot behavior is fixed then maybe we can consider whether to change the gray dot behavior too.

means that you can imagine working on a solution for https://github.com/elementary/calendar/issues/34 as well?

**Comment by mcclurgm** [comment] 2020-06-12 20:10
I'm not sure honestly. I think that's a design issue more than an implementation issue for the moment, but if the core team agrees to do that then I'd be happy to give it a try.

**Closed** 2020-06-27 15:45 UTC
