### ISSUE TITLE
Can't add Google calendars.

### ISSUE THREAD

**Issue by kr428** [elementary/calendar#391] opened 2019-04-12 10:32 UTC
In my current installation I'm unable to add Google Calendars to elementary calendar. Process:

(1) Click on the cogwheel icon.
(2) Choose "add new calendar"
(3) Select "Google Calendar"
(4) Enter "name" and "user"
(5) Click on "create calendar"

Expectation would be (and I also have seen this working in earlier elementary installations) a pop-up window to authenticate with Google. That doesn't happen - instead, after "create calendar" I just fall back to the calendar list (the dialog I see in step (1)) and nothing else happens. Known issue? Workarounds available?
Thanks,
Kristian

**Comment by peteruithoven** [comment] 2019-04-12 10:45
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/calendar/issues/360

Quote from #16:
> Just leaving a comment here that I think the plan is to have all online accounts integration for Calendar go through Online Accounts in System Settings. So adding a calendar from an Google account inside of calendar itself will go away. Adding a calendar using Evolution and Google Oauth imports all calendars already, so that's what System Settings needs to do.

**Closed by peteruithoven** 2019-04-12 10:45 UTC

**Comment by kr428** [comment] 2019-04-12 10:47
Ah ok. Sorry, I just was reading across the description and it seemed a different issue to me. Thanks for clarifying. :+1:
