### ISSUE TITLE
Calendar not Installing on Arch 

### ISSUE THREAD

**Issue by rainer2208** [elementary/calendar#766] opened 2022-11-10 12:55 UTC
### What Happened?

I am on Arch Linux and have tried to install the calendar app in different ways, both failed. 

My first attempt was cloning the repo from Github and running the installation through ninja. 

The error list  contains 114 items, apparently all related to the libsoup package. This is an excerpt: 
```

libsoup-3.0.vapi:7.3-7.62: error: `Soup.Form' already contains a definition for `decode'
    7 | 		public static GLib.HashTable<weak string,weak string> decode (string encoded_form);
      | 		^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libsoup-2.4.vapi:7.3-7.62: note: previous definition of `decode' was here
    7 | 		public static GLib.HashTable<weak string,weak string> decode (string encoded_form);
      | 		^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libsoup-3.0.vapi:9.3-9.73: error: `Soup.Form' already contains a definition for `decode_multipart'
    9 | 		public static GLib.HashTable<weak string,weak string>? decode_multipart (Soup.Multipart multipart, string? file_control_name, out string filename, out string content_type, out GLib.Bytes file);

  libsoup-2.4.vapi:2131.2-2131.53: note: previous definition of `websocket_client_verify_handshake' was here
 2131 | 	public static bool websocket_client_verify_handshake (Soup.Message msg) throws GLib.Error;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libsoup-3.0.vapi:1034.2-1034.52: error: `Soup' already contains a definition for `websocket_server_check_handshake'
 1034 | 	public static bool websocket_server_check_handshake (Soup.ServerMessage msg, string? origin, [CCode (array_length = false, array_null_terminated = true)] string[]? protocols, GLib.GenericArray<GLib.TypeClass>? supported_extensions) throws GLib.Error;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                       
libsoup-2.4.vapi:2140.2-2140.52: note: previous definition of `websocket_server_check_handshake' was here
 2140 | 	public static bool websocket_server_check_handshake (Soup.Message msg, string? origin, [CCode (array_length = false, array_null_terminated = true)] string[]? protocols) throws GLib.Error;
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                          
libsoup-3.0.vapi:1036.2-1036.54: error: `Soup' already contains a definition for `websocket_server_process_handshake'
 1036 | 	public static bool websocket_server_process_handshake (Soup.ServerMessage msg, string? expected_origin, [CCode (array_length = false, array_null_terminated = true)] string[]? protocols, GLib.GenericArray<GLib.TypeClass>? supported_extensions, out GLib.List<Soup.WebsocketExtension> accepted_extensions);
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                     
libsoup-2.4.vapi:2146.2-2146.54: note: previous definition of `websocket_server_process_handshake' was here
 2146 | 	public static bool websocket_server_process_handshake (Soup.Message msg, string? expected_origin, [CCode (array_length = false, array_null_terminated = true)] string[]? protocols);
      | 	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      
```

I also tried to run the installation of the AUR package using Pamac, but it also failed when trying to install the dependency granite-git, with a long list of similar erros (excerpt): 

  ```
   conflicting files:
- granite-git: /usr/bin/granite-7-demo already exists in filesystem (owned by granite7)
- granite-git: /usr/include/granite-7/granite-7.h already exists in filesystem (owned by granite7)
- granite-git: /usr/lib/girepository-1.0/Granite-7.0.typelib already exists in filesystem (owned by granite7)
- granite-git: /usr/lib/libgranite-7.so already exists in filesystem (owned by granite7)
- granite-git: /usr/lib/libgranite-7.so.7 already exists in filesystem (owned by granite7)
- granite-git: /usr/lib/libgranite-7.so.7.1.0 already exists in filesystem (owned by granite7)
- granite-git: /usr/lib/pkgconfig/granite-7.pc already exists in filesystem (owned by granite7)
- granite-git: /usr/share/applications/io.elementary.granite-7.demo.desktop already exists in filesystem (owned by granite7)
- granite-git: /usr/share/gir-1.0/Granite-7.0.gir already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/aa/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/ab/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/ace/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/ae/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/af/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/ak/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/am/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/an/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/ar/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/as/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/ast/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/av/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/ay/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
- granite-git: /usr/share/locale/az/LC_MESSAGES/granite-7.mo already exists in filesystem (owned by granite7)
```

### Steps to Reproduce

1. Removed the calendar app 
2. Tried to reinstall using the git clone, meson and ninja build
3. Tried to build the AUR package with Pamac package manager 

### Expected Behavior

Install and run the application

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Hardware Info

ASUS VivoBook 
Intel i5
Arch Linux

**Comment by tintou** [comment] 2022-11-10 14:26
Duplicate of #756

**Closed by tintou** 2022-11-10 14:26 UTC
