### ISSUE TITLE
duplicate event after add new event

### ISSUE THREAD

**Issue by TheRock892** [elementary/calendar#600] opened 2020-09-28 08:16 UTC
Google Calendar events are listed twice afer add until calendar is closed and reopened

**Comment by TheRock892** [comment] 2020-09-28 08:17
if I delete the event, it remains an event entry until the closing and reopening of calendar

**Comment by mcclurgm** [comment] 2020-09-28 15:19
We just fixed this in #597, but it hasn't been released yet. This fix will be out in the next version though.

Duplicate of #478.

**Closed by mcclurgm** 2020-09-28 15:19 UTC
