### ISSUE TITLE
Dates Invisible in Calendar App

### ISSUE THREAD

**Issue by rainer2208** [elementary/calendar#764] opened 2022-10-17 14:10 UTC
### What Happened?

I installed Elementary on Arch Linux a couple month ago. 

The desktop is terrific and I love working with it, there is just one issue simular to the one I noted with the WingPanel Date-Time Indicator. I have filed an issue, 304, [here](https://github.com/elementary/wingpanel-indicator-datetime/issues/304#event-7566216151), which has already been solved. 

The dates in the calendar app are not visible, only the names of the events. 

![Calendar](https://user-images.githubusercontent.com/23400899/196198287-4459f80b-3b3e-4110-80b6-3c9a3b9b0b2e.png)

### Steps to Reproduce

Install Elementary normally on Arch 

### Expected Behavior

See the numbers of the dates 

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Hardware Info

Asus VivoBook with i5 Intel CPU

**Comment by tintou** [comment] 2022-10-17 14:28
Duplicate of #761

**Closed** 2022-10-17 14:28 UTC
