### ISSUE TITLE
Change colour in dark mode.

### ISSUE THREAD

**Issue by sysadmin-info** [elementary/calendar#552] opened 2020-06-24 20:56 UTC
https://elementaryos.stackexchange.com/questions/24515/unreadable-calendar-events-in-dark-mode/24984#24984

solution 

Change in /calendar-master/data/style/AgendaEventRow.css
.event {
    background: alpha(@accent_color, 0.15);
    border-radius: 3px;
    color: shade(@accent_color, 0.65);
    padding: 6px;
}

to

.event {
    background: alpha(@accent_color, 0.75);
    border-radius: 3px;
    color: shade(@accent_color, 0.35);
    padding: 6px;
}

**Comment by funder7** [comment] 2020-09-19 14:49
Hello, there's any chance to have this fix integrated into the app?

**Comment by danrabbit** [comment] 2020-10-09 21:44
Closing as a duplicate of #267

**Closed by danrabbit** 2020-10-09 21:44 UTC
Labels: Status: Duplicate
