### ISSUE TITLE
Cannot add google account

### ISSUE THREAD

**Issue by jegjessing** [elementary/calendar#385] opened 2019-03-27 14:24 UTC
I have tried adding a google account to the calendar on Elementary Juno.
But when I press Create Calendar, nothing happens..

**Comment by alainm23** [comment] 2019-03-27 16:54
See: https://elementaryos.stackexchange.com/questions/15245/unable-to-validate-gmail-mail-account-username-or-password-error

**Comment by jegjessing** [comment] 2019-03-27 17:04
Not relevant I have done this. Working fine in other clients not using two
factor

**Comment by peteruithoven** [comment] 2019-03-28 01:42
Thanks for the report! I'm afraid this sounds like a duplicate of #/112, #117 and  #244
Maybe #244 contains a useful workaround. 

This aspect is going to be overhauled in the near future.

**Closed by peteruithoven** 2019-03-28 01:42 UTC

**Comment by jegjessing** [comment] 2019-03-28 02:49
Well now I noticed that I cannot add a calendar at all. I tried to add a new calendar using "on this computer". Same result. Nothing happens. So the problem is not google at all

**Comment by ryonakano** [comment] 2019-03-28 03:24
I also can't add new calendars:

![2019-03-28 12 16 12 の画面録画](https://user-images.githubusercontent.com/26003928/55127472-94acd180-5153-11e9-9069-fef848da5508.gif)

By launching Calendar from Terminal, I got the following error message:

```
** (io.elementary.calendar:17789): CRITICAL **: 12:15:47.198: maya_local_backend_real_add_new_calendar: assertion 'color != NULL' failed
```

However, I can add when I select color of the calendar explicitly:

![2019-03-28 12 17 39 の画面録画](https://user-images.githubusercontent.com/26003928/55127473-94acd180-5153-11e9-975f-708514dcbd5a.gif)

@jegjessing Could you check whether you can add a new calendar by selecting color of it?

**Comment by ryonakano** [comment] 2019-03-28 03:47
https://github.com/elementary/calendar/blob/d7b9a09010d0cdaaf5194d59ddce08825065233e/src/SourceDialog/SourceDialog.vala#L27

I'm not 100% sure whether this is an appropriate way, but I suppose we may want to initialize `hex_color` to "#da3d41" (which is the hex color code of default selected red color) here.

**Comment by jegjessing** [comment] 2019-03-28 08:19
Yes, there it was. Now it's working perfectly, thanks,

*Med venlig hilsen / Best regards*
Jarl Gjessing
Mobil: +45 60 72 17 16
Adresse: Klintevej 7, DK-3600 Frederikssund
