### ISSUE TITLE
Windows timezones are not handled

### ISSUE THREAD

**Issue by dbustosrc** [elementary/calendar#572] opened 2020-07-14 23:43 UTC
I have connected my Office 365 calendar to Elementary Calendar application through public ics calendar.

**## Describe the bug**

ICS calendar content:
```
SUMMARY:Convite: IM0474 - Ecuador/Seidor Interface - PI - Semanal: de 10:00
  até 11:00 cada terça-feira de ter. 30 jun. até sáb. 15 ago. (BRT) ()
DTSTART;TZID=SA Pacific Standard Time:20200630T080000
DTEND;TZID=SA Pacific Standard Time:20200630T090000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200713T222111Z


SUMMARY:COMITE PARITARIO JULIO
DTSTART;TZID=SA Pacific Standard Time:20200714T150000
DTEND;TZID=SA Pacific Standard Time:20200714T160000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200713T222111Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Reunión de Microsoft Teams
```

DTSTART and DTEND has not "Z" suffix so that indicates that those datetime are not provided in UTC.  So I think that you don't need translate the timezone:
https://tools.ietf.org/html/rfc5545#section-3.2.19

**If applicable, add screenshots or screen recordings to help explain your problem.**

I'm using maya-calendar 5.0.6+r1806+pkg130~ubuntu5.1.5.1 and evolution too (it's fine on this). You can look the differences.
![87380020-33cb2780-c557-11ea-907f-bfcc77ee7a2e](https://user-images.githubusercontent.com/26286623/87486638-4f8b0800-c601-11ea-917d-60f21a72c024.png)
![87359305-25681600-c52d-11ea-9bef-160165dbbd3e](https://user-images.githubusercontent.com/26286623/87486639-50bc3500-c601-11ea-8263-c53bb2f09f43.png)

**### To Reproduce**
You can import ICS calendar without Z suffix in DTSTART and DTEND in Maya Calendar

**## Platform Information**
OS: elementary OS 5.1.6 Hera x86_64
Kernel: 5.3.0-62-generic

Related bugs: 
#92 
#50

**Comment by mcclurgm** [comment] 2020-07-20 16:44
I'd like to look at this, but I can't get this ICS file to import. Can you provide another one? If it helps, you can paste the contents of your file into the [iCalendar validator](https://icalendar.org/validator.html#l1) to make sure it works.

**Comment by mcclurgm** [comment] 2020-07-20 16:49
Sorry for lots of notifications, but I'm going to close this as a duplicate of #50, especially since you have all the info there too. Can you paste the full file over there please?

**Comment by mcclurgm** [comment] 2020-07-20 17:04
Nope, I did that too fast. Sorry! Looking closer, I think this is a separate issue from #50. It's not recognizing the timezone you set and thinks it's UTC, while that was taking a UTC time and thinking it's local. I'll have another look at this.

I did a bit of trial and error to make an ICS file that imports for me:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
DTSTART;TZID=SA Pacific Standard Time:20200714T150000
DTEND;TZID=SA Pacific Standard Time:20200714T160000
SUMMARY:Service Appt
LOCATION:**********
DESCRIPTION:Service Appointment for ******
END:VEVENT
END:VCALENDAR
```

**Comment by mcclurgm** [comment] 2020-07-20 20:32
Alright, I think I've found the root issue. I can't figure out how to fix it though. I'm leaving this here in case it sparks any ideas.
Seems like the problem is in how ECal handles its times (which is really weird...) It looks like it produces a `ComponentDateTime`, which has a `tzid` and `value` field. `value` is an ICalTime that we use, but discards its timezone info. So its time is 15:00, but doesn't include any timezone info. It behaves like a floating timezone (not UTC, but we treat it like UTC, which is another issue). The timezone info is stored in the `ComponentDateTime.tzid`.

As far as I can tell, with the API I can see, we have 2 options.
1. Instead of doing the Component->string->Component dance, we could in theory use `ECal.Component.from_icalcomponent`. This would keep all of the time info intact, because it would be the same object. But I can't get this to work, I think since it has ownership issues. It looks like the `ICal.Component` is freed as soon as the function exits, so it can't be used in any other part of the codebase. If there was a way to clone a `ICal.Component` and have it owned by us, that would be perfect, but I haven't seen any way to do that. (Haven't been able to verify this, but I do know that the program exits every time at the end of the function)
2. Coerce the parsed `Time` to have the right timezone info. I should be able to tell the `Time` that it's actually relative to a certain timezone, but I'm not sure how exactly. `convert_timezone` doesn't seem to do anything for these. It looks like `set_timezone` would be what we're looking for, but it's not in our VAPI and I'm having some trouble figuring out how to fix that.

I feel like the ideal is the first one if we can get it working, but I'm a little scared of tackling memory management and ownership...

**Comment by dbustosrc** [comment] 2020-07-25 21:59
Hi @mcclurgm 
If helps, I found a similar article from Gnome Calendar when same problem was happening on it. Also you can check the committed code too.
[Gnome Calendar Issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1714)
[Committed code](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/46543525e667a5a368dd494c2211f76b923c3565)

**Comment by mcclurgm** [comment] 2020-07-26 20:14
Thanks for the link! That's good info. 

For the sake of taking notes, it looks like they use `set_timezone` there, which I can't figure out how to get working. I'll give it another look.

One more thing, @dbustosrc could you confirm whether this is only when you import an ICS event or if you see it in other places?

**Comment by dbustosrc** [comment] 2020-07-27 03:18
@mcclurgm I have the problem only with ICS events.

**Comment by mcclurgm** [comment] 2020-07-27 15:40
Great, thanks for confirming!

**Comment by mcclurgm** [comment] 2020-07-27 17:32
Where did you get this ICS event from? I don't think we're capable of recognizing the timezone `SA Pacific Standard Time`. I tried the same ICS file, replacing that with `America/Los_Angeles` and it behaved just as expected, even in the current shipping build.

I'm worried that this may be an issue with the libraries we use, not our own code. If they can't recognize the timezone, then it just won't work.

**Comment by dbustosrc** [comment] 2020-07-27 21:18
I'm from Ecuador. I got the ICS file from my MS Office 365 Outlook account (Web Calendar).
You are right. I have many meetings, and I found another from different timezone instead of `SA Pacific Standard Time` in the same calendar and it's works correctly. So, the problem is `SA Pacific Standard Time` Timezone

I have added an ICS file with `SA Pacific Standard Time` as attachment for your review.
[Teams Meeting.zip](https://github.com/elementary/calendar/files/4984341/Teams.Meeting.zip)

And also two screenshots of how the event see on Maya and Evolution
![Evolution View](https://user-images.githubusercontent.com/26286623/88591147-83165b00-d021-11ea-8a04-7b674b16b8fc.png)
![Maya View](https://user-images.githubusercontent.com/26286623/88591155-86114b80-d021-11ea-9c6f-cd44082862f2.png)

And I have added an ICS file with `America/Bahia` Timezone as attachment for your review.
[America-Bahia.zip](https://github.com/elementary/calendar/files/4984431/America-Bahia.zip)

But as you can see, for this event is correct:
![Evolution View](https://user-images.githubusercontent.com/26286623/88593020-8828d980-d024-11ea-931c-a75b2e2cd151.png)
![Maya View](https://user-images.githubusercontent.com/26286623/88593054-9545c880-d024-11ea-935c-d406babb1638.png)

**Comment by mcclurgm** [comment] 2020-07-28 22:19
That's some good info, thanks. I can verify that your timezone works in Evolution, but neither elementary nor GNOME calendar apps. 

Based on this info it may be possible for us to fix this in our own code. I don't know what Evolution is doing differently, but it's working on the same system so it must be workable.

**Comment by dbustosrc** [comment] 2020-07-29 06:26
@mcclurgm 
I was investigating about the bug and I found the problem and the posible solution.
The problem is that Office 365 have `Windows Timezones`, and the library `libical` only works with Olson Timezones, and you need to translate the `Windows Timezone String` to `Olson Timezone String`.
I found in the code of evolution data server this function:
[ECal System Timezone](https://mail.gnome.org/archives/commits-list/2014-January/msg03647.html)
Look at the function `windows_timezone_string_to_olson`.
`{ "SA Pacific Standard Time", "America/Bogota" }`
`America/Bogota` is the Olson Timezone to `SA Pacific Standard Time`
I think that you can fix the bug by using a condition to parse the Timezone before that it's sending the Timezone String

**Comment by mcclurgm** [comment] 2021-02-26 16:51
New info from #652, which I'll add here. If an event with one of these timezones makes it into calendar, this same issue happens: we don't know what timezone it is. This can happen if you import an event through another app (like Evolution) or maybe if you sync an Exchange calendar.

**Comment by mcclurgm** [comment] 2021-06-05 18:13
Just as a status update, I'm working on fixing this now. I have a working branch based off of the discussion #660 which I have confirmed fixes this issue, at least for importing an event with the `W. Europe Standard Time` timezone.

**Closed** 2021-10-15 16:15 UTC
Labels: Status: In Progress, Status: Confirmed
