### ISSUE TITLE
The behaviour when creating new events should be logical and consistent with regard to the "mark as default calendar" option

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/calendar#553] opened 2020-06-25 13:48 UTC
![Screen_record cleaned](https://user-images.githubusercontent.com/46536067/85727370-792dcf00-b6e6-11ea-830e-b3832a0e81da.gif)

One thing irritates me:

At first glance, it seems that it is mandatory to define a default calendar in order to create an event. However, test5 & test6 can be created after I have already unchecked the default calendar option again. That seems inconsistent to me.

Beyond my observation, I wonder whether it should be necessary for the creation of new events to have at least one standard calendar defined before. And I also wonder if it should even be possible to start creating an event using the "Create an event" button without setting a default calendar. Or whether the button should remain insensitive until I have done so.

My expectation as a user would in any case be consistent behaviour.

I use the latest stable and unmodified Hera version including all updates.

Somehow also connected with this issue https://github.com/elementary/calendar/issues/544
Again, the "Create Event" dialog can be started, although it looks like the conditions for creating a new event are not yet fulfilled.

**Comment by mcclurgm** [comment] 2020-09-16 03:32
I have a feeling this is caused by #550, but I'm not sure. Since the check/uncheck behavior doesn't seem to work at all, I wouldn't be surprised if there actually is still a default calendar but the check box doesn't reflect that. This is all speculation though.

**Comment by 4jNsY6fCVqZv** [comment] 2020-09-16 07:43
Do you have an idea how we can find out and solve this?

**Comment by mcclurgm** [comment] 2020-09-20 23:54
No sorry... I've never dealt with that part of the codebase. I imagine that the signal we send when you click the check button may be wrong. If you have experience looking at our code, that's where I'd start, but I'm going to (work allowing) do that soon too.

**Comment by mcclurgm** [comment] 2020-09-25 18:37
We just fixed #550, so the checkbox behavior should be at least a little nicer. I don't really understand what the issue is here, so can you try rebuilding from git and let me know if you're still seeing it?

**Comment by 4jNsY6fCVqZv** [comment] 2020-10-02 08:03
Unfortunately I don't have time to rebuild it from git right now. Maybe someone else?

**Comment by mcclurgm** [comment] 2020-10-10 13:40
Fair enough. We just released an update with the changes, so if you have the time to give that a try that would be great! Otherwise no worries.

**Comment by mcclurgm** [comment] 2021-08-28 18:33
@4jNsY6fCVqZv Now that Odin is released, could you have a look and see if the issue still exists? I don't really understand what the issue is you're describing here, but the current release has the fix to the default calendar picker.

**Comment by 4jNsY6fCVqZv** [comment] 2021-08-31 08:05
@mcclurgm Haven't switched to Odin yet, I'll try as soon as possible.

**Comment by 4jNsY6fCVqZv** [comment] 2021-11-23 08:52
The issue I wanted to show is that once no default calendar is set, it is possible to create new events, but they are not shown in the calendar. I would expect that if it is a requirement that a default calendar has to be set, then without it there should be no way to create a new event. And then, if necessary, a notification appears that a default calendar must be set first.

I have tested it with Odin. With version 6.0.3 the last calendar is automatically the default calendar. The check mark cannot be removed and is grayed out. So I can close this issue with gratitude!

**Comment by 4jNsY6fCVqZv** [comment] 2021-11-23 09:20
I have experimented a bit more.
I create a new calendar Test1 in addition to the two preset calendars "Personal" and "Birthdays & Anniversaries" and marked it as the default calendar.
Afterwards I delete Test1 directly again. If I now create a new event without marking "Personal" as the new default calendar, I can create a new event, but it is not displayed in the calendar afterwards. By the way, if I mark "Birthdays & Anniversaries" as the default calendar after deleting Test1 and then try to create a new event, it does not show up in the calendar overview either.

**Comment by mcclurgm** [comment] 2021-11-24 17:02
Thanks for looking into this. That appears to be two separate issues: one is that you can remove the last calendar, and one is that you can set read-only calendars as default. I'm going to open new issues for each of those and close this, since it appears that the original issue around the default checkbox is fixed. If I'm misunderstanding, feel free to reopen.

One question: I'm not sure what you mean by the last sentence
> By the way, if I mark "Birthdays & Anniversaries" as the default calendar after deleting Test1 and then try to create a new event, it does not show up in the calendar overview either.

Could you please clarify? What do you mean by "calendar overview" and what doesn't appear, the event or the "Birthdays & Anniversaries" calendar?

**Closed** 2021-11-24 17:02 UTC

**Comment by 4jNsY6fCVqZv** [comment] 2021-11-29 14:13
Thanks for taking a closer look at the Issues!

> Could you please clarify? What do you mean by "calendar overview" and what doesn't appear, the event or the "Birthdays & Anniversaries" calendar?

I don't know what the exact name for it is right now. I just mean the normal month view.

And it is the event that does not appear for me.

**Comment by mcclurgm** [comment] 2021-11-29 17:03
That clears it up, thank you! I assume this is because the calendar is read only, but I’m not sure how to detect that. I’ll do a bit more digging and open a new issue when I’ve figured out the cause.

**Comment by 4jNsY6fCVqZv** [comment] 2021-11-30 15:10
Then this calendar probably shouldn't automatically become the default calendar, right? https://github.com/elementary/calendar/issues/726

Thank you for looking into the issue and creating more issues for it if necessary!
