### ISSUE TITLE
Headerbar button styling backwards in RTL

### ISSUE THREAD

**Issue by cassidyjames** [elementary/calendar#296] opened 2018-11-27 22:34 UTC
![2018-11-27 15 32 41](https://user-images.githubusercontent.com/611168/49116138-f28ae480-f259-11e8-8805-1675e76a5edc.png)

**Comment by danrabbit** [comment] 2018-12-04 00:55
Closing as a duplicate of https://github.com/elementary/stylesheet/issues/454

**Closed by danrabbit** 2018-12-04 00:55 UTC
