### ISSUE TITLE
Google Calendar events are listed twice afer add

### ISSUE THREAD

**Issue by camilova** [elementary/calendar#497] opened 2020-03-30 16:51 UTC
## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Describe the bug
Just after add an event through main app window for `google calendar`, it shows on the list at the right side but twice.
It should be only one time at list, and one time on "tomorrow" subsection of the same list; something is causing that after adding it renders the item twice.

![image](https://user-images.githubusercontent.com/29240376/77938573-4eb9aa80-728c-11ea-8342-518346871a3d.png)

But in the day square it shows correctly only one time.

![image](https://user-images.githubusercontent.com/29240376/77939106-08188000-728d-11ea-90cd-3b7385bc4b9f.png)

### To Reproduce
1. Double click on any day on the calendar from top panel on patheon to open calendar app.
2. Double click on the number of the day where you wanna add a new event.
3. Fill some data for the event and select a google calendar of the calendar option dropdown.
4. Add the event and it will be showed twice at the right side list, but one time (as we want) at the little square of the day on calendar.

### Expected behavior
It should render the item only one time at the right side list.

## Platform Information

Asus K501UW - Elementary OS 5.1.2 Hera

## Context
I have not tested this behaviours for other calendars different of google calendar.

**Comment by mcclurgm** [comment] 2020-03-30 20:05
This is a duplicate of #478.

**Closed** 2020-03-30 21:04 UTC
Labels: Status: Duplicate
