### ISSUE TITLE
Support for SSO with Google Accounts

### ISSUE THREAD

**Issue by joedborg** [elementary/calendar#410] opened 2019-07-19 18:35 UTC
Currently, only Google credentials are supported.  Some enterprises authenticate via their own SSO.  An example of this working is in Gnome Online Accounts.

**Comment by peteruithoven** [comment] 2019-07-19 18:42
I don't know what SSO is but should this be opened in our online accounts section?
https://github.com/elementary/switchboard-plug-onlineaccounts/issues

I know currently you still authenticate etc in calendar itself but more is going to move to the online accounts settings.

**Comment by danrabbit** [comment] 2019-07-19 18:43
Closing as a duplicate of https://github.com/elementary/calendar/issues/244

**Closed by danrabbit** 2019-07-19 18:43 UTC
