### ISSUE TITLE
Elementary 6: Calendar shows repetitive events with +1 increment

### ISSUE THREAD

**Issue by jcamposz** [elementary/calendar#652] opened 2021-02-25 07:01 UTC
In elementary 6, Calendar doesn't show correctly repetive events , these are shown with +1 increment.
![Bug_calendar](https://user-images.githubusercontent.com/11057356/109115563-8ac8ea00-773f-11eb-9425-617b4bd5e4aa.png)
 In this screenshot, it appears evolution calendar tab and elementary calendar app to compare differences.

My computer is in Spain time zone (GMT+1) .

**Comment by mcclurgm** [comment] 2021-02-25 16:01
Hmm, I tried to replicate this on my VM but everything looks as I expect. I made a repeating event and set it to a different time zone than my computer, but it shows at the same time as Evolution in my local timezone (at the proper time). 

Is there any chance you could paste the ICS file for one of the recurring events that you're seeing display wrong? I'd like to add them myself and see if there's anything unusual about them that we don't account for.

**Comment by jcamposz** [comment] 2021-02-26 12:31
Probably the only difference is these repetitive taks (in my case) are provided via external calendar
![imatge](https://user-images.githubusercontent.com/11057356/109300152-7b789800-7836-11eb-9a75-01c7ed6022d6.png)
I have attached ics file .
[calendar.ics.zip](https://github.com/elementary/calendar/files/6049655/calendar.ics.zip)

**Comment by mcclurgm** [comment] 2021-02-26 16:49
Thanks, that's just what I needed! It looks like the issue is with the time zone that your event is set to ("Western European Time"), which it looks like we don't recognize. By what I can tell, this is a duplicate of #572, although I didn't know that it could still happen once the event made it into Calendar. Thanks for the report! I'll move this info over there.

**Closed** 2021-02-26 16:50 UTC
