### ISSUE TITLE
Cannot add calendar without explicitly selecting color

### ISSUE THREAD

**Issue by knyzorg** [elementary/calendar#424] opened 2019-09-04 00:35 UTC
When adding a caldav calendar, I use the upper right gear icon, select "Add new Calendar", type "CalDAV", fill out the inputs as required and leave the default color as is (Red). I then click "Create calendar".

Desired behavior:
A calendar with the red color should be added. Alternatively, an error should be displayed if something went wrong.

Actual behavior:
The add menu silently closes, and a failed assertion is logged:
```
** (io.elementary.calendar:8346): CRITICAL **: 20:32:20.990: maya_cal_dav_backend_real_add_new_calendar: assertion 'color != NULL' failed
```

**Comment by ryonakano** [comment] 2019-09-04 01:11
Thank you for your reporting. I'm going to close this issue as a duplicate of #422.
Actually, it was fixed in #387, but a new version of Calendar that includes this fix has not been released yet.

**Closed by ryonakano** 2019-09-04 01:11 UTC
