### ISSUE TITLE
Add new event

### ISSUE THREAD

**Issue by SzyszkaWeb** [elementary/calendar#467] opened 2019-11-27 21:55 UTC
Good evening,
When I try to add new event on Calendar, the Calendar close. I try to open this from top panel, aplication and dock and problem is the same. After reinstall system it was work. 
I dont know all of linux because im newbie and i get know new things all time

**Comment by danrabbit** [comment] 2019-11-27 21:58
Closing as a duplicate of #464

**Closed by danrabbit** 2019-11-27 21:58 UTC
