### ISSUE TITLE
Can't click calendars outside of window when importing events

### ISSUE THREAD

**Issue by peteruithoven** [elementary/calendar#383] opened 2019-03-03 21:56 UTC
When I import a .ics file I can't seem to select the calendars that fall above the import window:
![screen record from 2019-03-03 22 50 25](https://user-images.githubusercontent.com/523210/53702438-37995680-3e07-11e9-8969-d586c328077a.gif)

I notice that I interact with the calendar app below, when I double click on an calendar tha'ts above a day from the previous month the calendar will navigate to that month. 

Might need the same fix as: https://github.com/elementary/calendar/issues/299

**Comment by danrabbit** [comment] 2019-03-03 22:09
I'd say this is probably a duplicate of #299

**Closed by danrabbit** 2019-03-03 22:09 UTC
