### ISSUE TITLE
There's something very wrong with the Calendar app

### ISSUE THREAD

**Issue by michalzkosmosu** [elementary/calendar#483] opened 2020-01-05 15:40 UTC
I'll start with the positive things.

The Calendar app in elementary OS is the most beautiful and elegant I have seen in all distros. It is also amazing that the applet in the top panel is a shortcut to the calendar itself and that it displays the events of today. Kudos for that. This is an excellent direction.

But there's something very wrong with the Calendar app and its applet, what you start to notice when you use it intensively.

Sometimes it shows the events for today correctly. Another time it shows 'No Events on This Day', even though there are several things planned for this day.

When you add new events, they sometimes appear normally. Another time, they don't show up at all. So you add them again. And they don't show up again. Then you close the app and open it again, seeing the lost event twice. Or you restart and still can't see them. So you add again and again and again. And then you get nervous and stop trying. The next day you run the Calendar to check something else and suddenly you see that lost event from yesterday added several times.

The calendar is a very important app. It would be wonderful if it worked properly.

**Comment by michalzkosmosu** [comment] 2020-01-05 15:44
Or when I add an event that is to take place annually and the Calendar adds a version of that event that is to take place weekly.

**Comment by wolframroesler** [comment] 2020-04-09 15:30
You are totally right (with both your positive and negative remarks). The Calendar app has embarrassingly many problems like those you mentioned, so many that I'm wondering if the developers actually use it themselves. I made a small modification (#475), and testing my changes revealed so many things that didn't work properly that it was hard for me to tell if I made a mistake. I'm currently trying to understand the internals of the app sufficiently to understand where the problems come from and how they can be remedied. Doesn't help that the source code is essentially comment-free.

Also, I think a comment such as yours should not go without feedback from the maintainers for months in a well-supported app ...

**Comment by mkykadir** [comment] 2020-04-09 18:31
I think a specific task should be opened for testing the application for its purposes. Also I think, it might also try very hard event creation and editing and many bugs are caused by those features. I am investigating recurring events now and it seems all buggy.

**Comment by wolframroesler** [comment] 2020-04-10 13:53
Well, automatic testing of GUI applications is a thing. Don't know if and how the Gtk/Vala framework supports it but it's definitely something the elementaryOS people should look into. One could plug in a mock-up layer instead of the Evolution API so that the tests can run without an actual online calendar being present. That's not rocket science, just plain software testing 101.

Funny you mention problems with recurring events because that's exactly what people are complaining about in that modification I made (issue #475, PR #476).

**Comment by cassidyjames** [comment] 2020-04-11 14:55
Thanks for your report. Unfortunately this is really not actionable as it is reporting what seems like several issues. For us to identify and fix issues, it is important that issue reports are clear, precise, and actionable. 

>I'm wondering if the developers actually use it themselves.

We do, but I know I personally am not a calendar-heavy user. I don't frequently use all the possible features of a calendar in my daily life, so sometimes it is hard to ensure it is well-tested.

>Also, I think a comment such as yours should not go without feedback from the maintainers for months in a well-supported app...

We have hundreds of issues, pull requests, comments, and mentions to review daily. I'm sorry this fell through the cracks, but I'm also not sure what else to say. Individually-filed issues with clear steps to reproduce (using the issue templates we've taken time to provide) help us identify, confirm, and fix reported issues.

I'm going to close this issue, but I'll try to take some time to search through existing issues and report any new ones you have mentioned here if they don't already exist.

**Closed by cassidyjames** 2020-04-11 14:55 UTC

**Comment by wolframroesler** [comment] 2020-04-12 12:47
Fair enough. I understand that this issue is a rant from a frustrated user rather than a precise bug report, but that also means that the problem behind it is deeper than it seems at first glance. For example, why is there a bug in editing a recurring event? Because it's not covered in unit tests. Why are there no unit tests for this particular feature? Because there don't seem to be any unit tests in this project. Why not? Because there is no established, simple unit-testing framework for Vala, let alone one that supports GUI tests. Why not use valadate? Because it seems to be discontinued and there's no obvious replacement. Why is Calendar the only app in the elementaryOS ecosystem affected by these issues? Well, unfortunately it isn't, I've seen seemingly obvious bugs in many others. So, we're really opening a can of worms here.

What's your opinion on that, @cassidyjames? Do you think automated testing could be useful in improving the quality of this (or other) apps, and/or make developer life easier (assuming there was something like an easy-to-use testing framework)? I'd love to help tackle these issues, rather than chiming into the rant.

**Comment by mcclurgm** [comment] 2020-06-11 04:49
@wolframroesler I can't speak for the maintainers, but I think that if you want to add some tests, feel free to do so! I've added some basic testing for a PR I'm working on (I was actually told to by a maintainer, which implies that they believe in this somewhat), and it would probably be a good idea to add some more for other things. If there's something you want to generate tests for, open a new PR for those changes? In my opinion, the worst they could say is no, but I don't expect they would.

The testing framework of choice seems to be [GLib Testing](https://developer.gnome.org/glib/stable/glib-Testing.html). Then you can use Meson to run the tests themselves. Here's an example project that uses  this framework: https://github.com/elementary/music/tree/master/core/Tests.
